name: JusticeAdvMacros
main: net.justicecraft.JusticeAdvMacros.Core
author: unv_annihilator
website: http://www.justicecraft.net
version: 1.2.5.4
commands:
  macro:
    description: Base command for macros
    usage: |
       /macro create <name>
       /macro set var <#>
       /macro undo line
       /macro set line <line>
       /macro save <name>
       /macro delete <name>
       /macro list
       /macro list <name>
       /macro <name>